import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const analyzeCode = async (codeSnippet: string): Promise<AnalysisResult> => {
  if (!codeSnippet.trim()) {
    throw new Error("Please enter some code to analyze.");
  }

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: `Analyze the following code snippet. 
    1. Identify the programming language.
    2. Estimate the probability (0-100) that this code was generated by an AI (LLM) rather than a human. 
       - Look for hallmarks of AI code: excessive comments explaining obvious things, generic variable names, very standard/textbook implementations, or hallucinated libraries.
       - Look for hallmarks of Human code: idiosyncratic naming, specific domain logic, "clever" one-liners, inconsistent formatting (if pasted raw), or legacy patterns.
    3. Provide a concise reasoning for your score.
    4. List 3 key features that influenced this decision.
    5. Review the code for bugs, logic errors, or style inconsistencies. Provide a "correctedCode" version that fixes these issues. If the code is already correct, provide an optimized or cleaner version (e.g., better variable names, modern syntax).

    Code Snippet:
    \`\`\`
    ${codeSnippet}
    \`\`\`
    `,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          language: {
            type: Type.STRING,
            description: "The detected programming language (e.g., Python, JavaScript, C++).",
          },
          aiProbability: {
            type: Type.NUMBER,
            description: "A number between 0 and 100 representing the likelihood of AI generation.",
          },
          reasoning: {
            type: Type.STRING,
            description: "A short paragraph explaining the verdict.",
          },
          keyFeatures: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "A list of 3 specific observations about the code style or structure.",
          },
          correctedCode: {
            type: Type.STRING,
            description: "The fixed, corrected, or optimized version of the input code.",
          },
        },
        required: ["language", "aiProbability", "reasoning", "keyFeatures", "correctedCode"],
      },
    },
  });

  const text = response.text;
  if (!text) {
    throw new Error("No response received from Gemini.");
  }

  try {
    return JSON.parse(text) as AnalysisResult;
  } catch (e) {
    console.error("Failed to parse JSON", text);
    throw new Error("Failed to parse analysis results.");
  }
};
